/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/Extra2.glb 
*/

import React, { useRef , useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Extra2(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Extra2.glb')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    actions.play();
    console.log(animations);
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Mobile" position={[-0.14, 0.815, 0.514]} rotation={[2.243, -0.53, 0.575]}>
          <group name="Camera_Front_PhoneButton_Mat_0" position={[0.028, -0.029, -0.09]} rotation={[-0.911, 0.668, -2.772]} scale={0.002}>
            <mesh name="Camera_Front_PhoneButton_Mat_0_1" geometry={nodes.Camera_Front_PhoneButton_Mat_0_1.geometry} material={materials.PhoneButton_Mat} />
            <mesh name="Camera_Front_PhoneButton_Mat_0_2" geometry={nodes.Camera_Front_PhoneButton_Mat_0_2.geometry} material={materials.PhoneCase_Mat} />
            <mesh name="Camera_Front_PhoneButton_Mat_0_3" geometry={nodes.Camera_Front_PhoneButton_Mat_0_3.geometry} material={materials.PhoneFace_Mat} />
            <mesh name="Camera_Front_PhoneButton_Mat_0_4" geometry={nodes.Camera_Front_PhoneButton_Mat_0_4.geometry} material={materials.Camera_Light1} />
          </group>
        </group>
        <group name="rig">
          <primitive object={nodes.c_pos} />
          <primitive object={nodes.c_arms_polel} />
          <primitive object={nodes.c_arms_poler} />
          <primitive object={nodes.c_foot_ikr} />
          <primitive object={nodes.c_leg_poler} />
          <primitive object={nodes.c_foot_ikl} />
          <primitive object={nodes.c_leg_polel} />
          <primitive object={nodes.c_hand_ikr} />
          <primitive object={nodes.c_hand_ikl} />
          <primitive object={nodes.root_refx} />
          <skinnedMesh name="rp_carla_rigged_001_geo" geometry={nodes.rp_carla_rigged_001_geo.geometry} material={materials['Material.001']} skeleton={nodes.rp_carla_rigged_001_geo.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Extra2.glb')
